FROM tomcat:8.0-jre8

MAINTAINER Rajaram Kaliyaperumal <rr.kaliyaperumal@gmail.com>

# Make rdc-demo-dataset dir
RUN mkdir -p /usr/local/tomcat/webapps/rdc-demo-dataset

# Copy rdf files requried for demonstrator tool
COPY rdc-demo-dataset /usr/local/tomcat/webapps/rdc-demo-dataset