version: "3.0"
services:
  # FDP for patient registry
  fdp-reg:
    image: dtlfair/fdp:latest
    ports:
      - "8500:8080"
    networks:
      - demo-net

  # FDP for biobank 
  fdp-biobank:
    image: dtlfair/fdp:latest
    ports:
      - "8501:8080"
    networks:
      - demo-net

  # FDP for the fairfier 
  fdp-fairfier:
    image: dtlfair/fdp:healthRiAgraph
    ports:
      - "8502:8502"
    depends_on:
      - agraph
    networks:
      - demo-net
    extra_hosts:
      - "localhost:"

  # Create simple server to host rdf files required by demonstrator
  simple-server:
    build: ./simple-server
    ports:
      - "8503:80"
    networks:
      - demo-net

  # Blazegraph for the demonstrator
  blazegraph:
    image: rajireturn/blazegraph
    ports:
      - "8504:8504"
    #networks:
    #  - demo-net
    #network_mode: host
    networks:
      - demo-net
    extra_hosts:
      - "localhost:"

  # demonstrator 
  demo-app:
    image: dtlfair/fair-data-demo:healthRI2017
    ports:
      - "8505:80"
    networks:
      - demo-net
    extra_hosts:
      - "localhost:"

  # search
  fdp-search:
    image: dtlfair/fdp:latest
    environment:
   #   - LOAD_EXAMPLE_DATA=true
      - ES_URL=http://127.0.0.1:8506/fse/rs/
    ports:
      - "8507:80"
      - "8506:8080"
    extra_hosts:
      - "localhost:"

  # agraph 
  agraph:
    image: franzinc/agraph:v6.1.1
    ports:
     - "10035:10035"
    networks:
      - demo-net

  #fairfier
  fairifier:
    image: dtlfair/fairifier:latest
    ports: 
      - "8510:3333"
    networks:
      - demo-net
    extra_hosts:
      - "localhost:"

  #virtuoso
  virtuoso:
     image: tenforce/virtuoso:latest
     ports:
       - "8508:8890"
     environment:
       - DBA_PASSWORD=dba
     networks:
       - demo-net

  # Script for pre populatingfdp with idcards metadata
  idcard-prepopu-script:
    build : ./idcard-prepopulate-script
    depends_on:
      - "fdp-reg"
      - "fdp-biobank"
    networks:
      - demo-net
    extra_hosts:
      - "localhost:"

networks:
  demo-net:
    driver: bridge
