version: "3.0"
services:
  # FDP for RIVM
  fdp-rivm:
    image: dtlfair/fdp:latest
    ports:
      - "8500:8080"
    networks:
      - demo-net

  # Create simple server to host rdf files required by demonstrator
  simple-server:
    build: ./simple-server
    ports:
      - "8503:80"
    networks:
      - demo-net

  # Blazegraph for the demonstrator
  blazegraph:
    image: rajireturn/blazegraph
    ports:
      - "8080:8080"
    networks:
      - demo-net

  # demonstrator 
  demo-app:
    image: dtlfair/fair-data-demo:healthRI2017
    ports:
      - "8505:80"
    networks:
      - demo-net

  # Script for pre populatingfdp with rivm metadata
  rivm-prepopu-script:
    build : ./rivm-prepopulate-script
    depends_on:
      - "fdp-rivm"
    network_mode: host

networks:
  demo-net:
    driver: bridge