version: "3.0"
services:
  # FDP for RIVM
  fdp-rivm:
    image: dtlfair/fdp:latest
    ports:
      - "8500:8080"

  # FDP for mappings
  fdp-mappings:
    image: dtlfair/fdp:latest
    ports:
      - "8501:8080"  

  # Create simple server to host rdf files required by demonstrator
  simple-server:
    build: ./simple-server
    ports:
      - "8503:80"

  # Blazegraph for the demonstrator
  blazegraph:
    image: rajireturn/blazegraph
    ports:
      - "8504:8504"
    network_mode: host

  # demonstrator 
  demo-app:
    build: ./demonstrator
    ports:
      - "8505:80"

  # search
  fdp-search:
    image: dtlfair/search:latest
    environment:
   #   - LOAD_EXAMPLE_DATA=true
      - ES_URL=http://localhost:8080/fse/rs/
    #ports:
    #  - "8507:80"
    #  - "8506:8080"
    #extra_hosts:
    #  - "localhost:127.0.0.1"
    network_mode: host    

  # Script for pre populatingfdp with rivm metadata
  rivm-prepopu-script:
    build : ./rivm-prepopulate-script
    depends_on:
      - "fdp-rivm"
    network_mode: host