PREFIX sio: <http://semanticscience.org/resource/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT DISTINCT ?fdpURI ?fdp ?collectionURI ?collection ?description {

  VALUES(?input) {("biobank")}

  GRAPH ?distributionURI {
    ?collectionURI a sio:SIO_000756;
                   dcterms:title ?collection;
                   dc:description ?description.

  }

  FILTER ( regex(str(?collection), ?input, "i") || regex(str(?description), ?input, "i")) .

  GRAPH ?fdpURI {

	?datasetURI dcat:distribution ?distributionURI.
  }

  {
    ?fdpURI dcterms:title ?fdp
  }

}